osx_image: xcode8.3
sudo: required
dist: trusty
language: node_js
node_js: '8'
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
matrix:
  include:
  - os: osx
  - os: linux
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"

script:
- npm run release
