environment:
  nodejs_version: "8"

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version

build_script:
  - npm run release

shallow_clone: true
clone_depth: 1